### PR TITLE
fix(Header): show Browse Hotels only in hotel details view

### LINKED ISSUE #50: Display the "Browse Hotels" menu item only on hotels detail page
The item makes no sense on the homepage, so we should remove it from there.

image

### PR DESCRIPTION
**Pull request by PabloAlice**
fix #50

### CODE REVIEW

File: src/components/Header/index.jsx [hunk 1]
```diff
@@ -6,14 +6,16 @@ export default () => (
     <nav className="navbar navbar-expand-xl navbar-light" id="navbar">
       <div className="container">
         <Link className="navbar-brand mr-2" to="/">Winding Tree</Link>
-
+        {/hotels\/.*/.test(window.location.pathname)
```
Comment (JirkaChadima) [inline src/components/Header/index.jsx]: I'm not sure if this is the right way to do this, using `window.location` is kind of scary. I'd be much more comfortable with using [React Router's location](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/location.md). But I'm not really sure if it can be used here.

Comment (PabloAlice) [reply src/components/Header/index.jsx]: I don't see any difference between them, except for the state that we don't need yet.
Actually, I would have liked to use the Route component, but I got some issues and I thought that wouldn't be needed to spend more time in this issue for now.
if you still want a more robust solution, I can take a look and check why the Route component didn't work before.
